data_path: /home/platonics/Documents/calibration_ws/src/kinematics_calibration/data/panda_6/front
end_effector: ball_link
number_samples: null
offset_distance: 0.05
overwrite: true
regularizer: 0.0001
robot-name: panda_6
robot_name: panda_6
root_link: base_link
saving_steps: false
urdf: panda
variance: 0.0
